### ISSUE TITLE
How can be defined active participant in the group call?

### ISSUE THREAD

**Issue by RomanMolchanov2017** [Microsoft/BotBuilder-RealTimeMediaCalling#10]
We subscribe `AudioSocket.AudioMediaReceived` and `AudioSocket.DominantSpeakerChanged` events. When the `AudioMediaReceived` event is raised we have a raw audio chunk. We send this audio chunk to the transcriber as you demonstrated in the HueBot sample. But we can't define which participant this audio chunk belongs to. Therefore we use `DominantSpeakerChanged` event to save dominant speaker ID. But this event is raised with a big delay after the current dominant speaker changes.

What is the best way to define which speaker a currently received audio chunk belongs to?

**Comment by MalarGit** [comment]
Hi Roman, ActiveSpeakers in the AudioMediaBuffer will give you that information. Please note that this feature will be disabled soon. It will be reenabled when we fix the privacy controls. We are still working on the timeframe for reenabling.
