### ISSUE TITLE
NV12 Video format

### ISSUE THREAD

**Issue by kkabza** [Microsoft/BotBuilder-RealTimeMediaCalling#11]
Any pointers for creating videos that are compatible for playback using the real time media library? I have uploaded a few samples and cant seem to get them to stream across. I see in the source code it requires NV12 Frames.

**Comment by MalarGit** [comment]
You could convert the videos that you have with ffmpeg into NV12 format before streaming through the library. https://ffmpeg.org/ffmpeg.html

**Comment by kkabza** [comment]
Thats what I did and its working.
