### ISSUE TITLE
AudioVideoPlayerBot  audio and video files not saved.

### ISSUE THREAD

**Issue by gfclaveria** [Microsoft/BotBuilder-RealTimeMediaCalling#18]
Hi,

I just want to know how to properly setup the file locations setting. I tried to deploy and test the AudioVideoPlayerBot sample you have and it seems that no audio and video are being saved.

 _< Setting name="AudioFileLocation" value="$audioFileLocation$" / >
 < Setting name="VideoFileLocation" value="$videoFileLocation$" / >_

some questions regarding the above setting:
- what should be? directory/folder name or absolute filename with path?
- where should this be located? local from within the app location on the VM or on Azure Storage?

I also noticed that the MediaSession gets disposed immediately after the bot accepts the call, according to the logs

Also on the logs,  I'm getting this exception whenever i do video call:

**EventName="MessageEvent" Message="[4710da0c-dc55-4966-bcca-b50dfe8b7323 ForgetAndLogException,Utilities.cs(30)] Caught an Exception running the task: The given path's format is not supported.  StackTrace:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)   at FrontEnd.Utilities.CreateVideoMediaBuffers(Int64 currentTick) in C:\AVBot\FrontEnd\Utilities.cs:line 43   at FrontEnd.Call.MediaSession.<StartAudioVideoFramePlayer>d__26.MoveNext() in C:\AVBot\FrontEnd\CallLogic\MediaSession.cs:line 306--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at FrontEnd.Utilities.<ForgetAndLogException>d__0.MoveNext() in C:\AVBot\FrontEnd\Utilities.cs:line 25" TraceSource="FrontEnd"**

I'm suspecting its the fileLocation settings, or maybe I'm wrong.  :-(

Please help.

.

**Comment by gfclaveria** [comment]
Sorry, I'm closing this issue.  I miss understood how the sample bot works.

**Comment by aarushi-mittal** [comment]
Hi @gfclaveria ,
I am working on the same thing.

Were you able to find out if the bot had capability to read audioStreams or if we can implement it without creating any compliance policy ?

Regards,
Aarushi
