### ISSUE TITLE
There was an error completing this request due to an internal channel failure - BOT 

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder-RealTimeMediaCalling#6]
Hello
For past 2 weeks i am facing error "There was an error completing this request due to an internal channel failure" with my bot. BOT App id is "cc35e86c-faf5-4032-aef8-448f47bac745".
It used to work fine earlier from different skype ids. Since last week it started throwing above error for infy_97814@outlook.com login. But with other ids there are no issues. Can you please help.

**Comment by MalarGit** [comment]
How are you testing the bot? Making calls/sending messages? Could you try sending message from your outlook account and see if that works?

**Comment by neetgupta7** [comment]
Thanks for the reply. I am testing my bot from Skype channel by sending messages. I am logged into skype from the same outlook account and its giving error. I also deployed a new app service for the bit and re-registered it on bot portal but the error remains.

**Comment by neetgupta7** [comment]
I added a try catch block and now i see below exception message - "Response status code does not indicate success: 401 (Access Denied)". Please note i m also using LUIS dialog.

**Comment by MalarGit** [comment]
Could you post here? https://github.com/microsoft/BotBuilder/issues. This GitHub is only for real-time media.

**Comment by neetgupta7** [comment]
Sure...Thanks
